# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import openapi_client
from openapi_client.paths.bare_metals_baremetal_id import patch  # noqa: E501
from openapi_client import configuration, schemas, api_client

from .. import ApiTestMixin


class TestBareMetalsBaremetalId(ApiTestMixin, unittest.TestCase):
    """
    BareMetalsBaremetalId unit test stubs
        Update Bare Metal  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = patch.ApiForpatch(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 202




if __name__ == '__main__':
    unittest.main()
